DROP TABLE IF EXISTS `TB_MINIFC_SERVICE_INFO`;
CREATE TABLE `TB_MINIFC_SERVICE_INFO` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `serviceName` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '服务名称',
  `description` VARCHAR(512) DEFAULT '' COMMENT '描述信息',
  `createTime` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `updateTime` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_serviceName` (`serviceName`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='服务信息表';

DROP TABLE IF EXISTS `TB_MINIFC_FUNCTION_INFO`;
CREATE TABLE `TB_MINIFC_FUNCTION_INFO` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `serviceName` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '服务名称',
  `functionName` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '函数名称',
  `description` VARCHAR(512) DEFAULT '' COMMENT '描述信息',
  `execEnviroment` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '运行环境',
  `functionEntrance` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '函数入口',
  `functionVersion` INT(11) NOT NULL DEFAULT 1 COMMENT '函数版本号',
  `sourceCode` MEDIUMTEXT COMMENT '函数源代码',
  `uploadFilePath` VARCHAR(128) COMMENT '上传的文件路径',
  `createTime` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `updateTime` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_serviceName_functionName` (`serviceName`,`functionName`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='函数信息表';

DROP TABLE IF EXISTS `TB_MINIFC_TRIGGER_INFO`;
CREATE TABLE `TB_MINIFC_TRIGGER_INFO` (
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT COMMENT 'id',
  `serviceName` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '服务名称',
  `functionName` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '函数名称',
  `triggerType` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '运行环境',
  `triggerName` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '触发器名称',
  `triggerConfig` VARCHAR(4096) NOT NULL DEFAULT '' COMMENT '触发器配置(json格式)',
  `createTime` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `updateTime` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_service_function_trigger` (`serviceName`,`functionName`,`triggerName`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='触发器信息表';